<h1>*********************************ASSIGNMENT 3************************************</h1>

<b>Task 1:  
  1.  
Write a function to compute 5/0 and use try/except to catch the exceptions. </b>

In [1]:
def divide(x, y): 
    try:  
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
        print("Denominator has to be greater than zero")

divide(5, 0) 

Sorry ! You are dividing by zero 
Denominator has to be greater than zero


<b>
2.
    
    Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].  
Hint: Subject,Verb and Object should be declared in the program as shown below.  
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]  
Output should come as below:  

    Americans  play Baseball.

    Americans  play Cricket. 

    Americans  watch Baseball. 

    Americans  watch Cricket.


    Indians play Baseball. 

    Indians play Cricket. 
    
     Indians watch Baseball. 

    Indians watch Cricket.</b> 

In [2]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

sentence=[(i +" " + j + " "+ k) 
           for i in subjects
           for j in verbs
           for k in objects]
for l in sentence:
           print(l)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


<b>
    Task 2:    

    1.   
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.   
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-               Theophile Vandermonde. </b>

<H4>****CUSTOM FUNCTION***</H4>

In [3]:
def vander(vec,pow):
    return [[x**i 
             for i in range(pow-1,-1,-1)]
             for x in vec]
input_vector=[1,2,3,5]
vec=[int(i) for i in input_vector]
pow=4
output_matrix=vander(vec,pow)
print("Vandermonde matrix :")
print('\n'.join(["\t".join([str(x) for x in j]) for j in output_matrix]))

Vandermonde matrix :
1	1	1	1
8	4	2	1
27	9	3	1
125	25	5	1


<b>INBUILT -FUNCTION</b>

In [5]:

import numpy as np

x = np.array([1, 2, 3, 5])
N = 4
np.vander(x, N)
np.column_stack([x**(N-1-i) for i in range(N)])

x = np.array([1, 2, 3, 5])
print('vandermonde matrix: ')
print(np.vander(x))



vandermonde matrix: 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
